<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="6" failed="1" total="9" passed="2">
  <reporter-output>
    <line>
      <![CDATA[[INFO]: The test Browser is FIREFOX !!!]]>
    </line>
    <line>
      <![CDATA[[INFO]:  The application url is :- http://s-login.cengage.com/]]>
    </line>
    <line>
      <![CDATA[[ASSERT PASS]: PageTitle for NG-30181-LoginPage contains: 'Cengage Learning - Login'.]]>
    </line>
    <line>
      <![CDATA[[INFO]: log into the application using credentials 'kajal.inst@qaittest.com / A111111']]>
    </line>
    <line>
      <![CDATA[[ASSERT PASS]: PageTitle for NG-30181-InstructorPage contains: 'Instructor SSO - Instructor Resource Center'.]]>
    </line>
    <line>
      <![CDATA[[ASSERT PASS]: element pageTitle with text Instructor Resource Center is displayed.]]>
    </line>
    <line>
      <![CDATA[[ASSERT PASS]: element courseOperation with text Manage Course is displayed.]]>
    </line>
    <line>
      <![CDATA[[ASSERT PASS]: element btnAddInstructorTA is displayed.]]>
    </line>
    <line>
      <![CDATA[[ASSERT PASS]: element inputEmailId is displayed.]]>
    </line>
    <line>
      <![CDATA[[ASSERT PASS]: element btnAdd is displayed.]]>
    </line>
    <line>
      <![CDATA[[ASSERT FAIL]: Element courseLink not found on the NG-30181-InstructorManageCourses !!!]]>
    </line>
    <line>
      <![CDATA[[INFO]: The Test: NG_30181_TC03_INSTRUCTOR_CREATES_COURSE COMPLETED!
]]>
    </line>
  </reporter-output>
  <suite name="com.qait.mindtap.tests.NG_30104.NG_30181_TC04_Instructor_Launch_the_Course" duration-ms="118033" started-at="2015-10-01T12:08:28Z" finished-at="2015-10-01T12:10:26Z">
    <groups>
    </groups>
    <test name="Command line test 8a156310-bcfb-4614-854c-9563abd6972e" duration-ms="118033" started-at="2015-10-01T12:08:28Z" finished-at="2015-10-01T12:10:26Z">
      <class name="com.qait.mindtap.tests.NG_30104.NG_30181_TC04_Instructor_Launch_the_Course">
        <test-method status="PASS" signature="start_test_session(java.lang.String)[pri:0, instance:com.qait.mindtap.tests.NG_30104.NG_30181_TC04_Instructor_Launch_the_Course@17f6480]" name="start_test_session" is-config="true" duration-ms="7820" started-at="2015-10-01T17:38:28Z" finished-at="2015-10-01T17:38:36Z">
          <params>
            <param index="0">
              <value is-null="true"/>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[[INFO]: The test Browser is FIREFOX !!!]]>
            </line>
            <line>
              <![CDATA[[INFO]:  The application url is :- http://s-login.cengage.com/]]>
            </line>
          </reporter-output>
        </test-method> <!-- start_test_session -->
        <test-method status="PASS" signature="Step_01_Instructor_Logs_in_to_the_Application()[pri:0, instance:com.qait.mindtap.tests.NG_30104.NG_30181_TC04_Instructor_Launch_the_Course@17f6480]" name="Step_01_Instructor_Logs_in_to_the_Application" duration-ms="29825" started-at="2015-10-01T17:38:36Z" finished-at="2015-10-01T17:39:06Z">
          <reporter-output>
            <line>
              <![CDATA[[ASSERT PASS]: PageTitle for NG-30181-LoginPage contains: 'Cengage Learning - Login'.]]>
            </line>
            <line>
              <![CDATA[[INFO]: log into the application using credentials 'kajal.inst@qaittest.com / A111111']]>
            </line>
            <line>
              <![CDATA[[ASSERT PASS]: PageTitle for NG-30181-InstructorPage contains: 'Instructor SSO - Instructor Resource Center'.]]>
            </line>
          </reporter-output>
        </test-method> <!-- Step_01_Instructor_Logs_in_to_the_Application -->
        <test-method status="PASS" signature="takeScreenshotonFailure(org.testng.ITestResult)[pri:0, instance:com.qait.mindtap.tests.NG_30104.NG_30181_TC04_Instructor_Launch_the_Course@17f6480]" name="takeScreenshotonFailure" is-config="true" duration-ms="2" started-at="2015-10-01T17:39:06Z" finished-at="2015-10-01T17:39:06Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Step_01_Instructor_Logs_in_to_the_Application status=SUCCESS method=NG_30181_TC04_Instructor_Launch_the_Course.Step_01_Instructor_Logs_in_to_the_Application()[pri:0, instance:com.qait.mindtap.tests.NG_30104.NG_30181_TC04_Instructor_Launch_the_Course@17f6480] output=[ASSERT PASS]: PageTitle for NG-30181-LoginPage contains: 'Cengage Learning - Login'.]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- takeScreenshotonFailure -->
        <test-method status="PASS" signature="Step_02_Instructor_Manages_Course_From_SSO()[pri:0, instance:com.qait.mindtap.tests.NG_30104.NG_30181_TC04_Instructor_Launch_the_Course@17f6480]" name="Step_02_Instructor_Manages_Course_From_SSO" duration-ms="21079" started-at="2015-10-01T17:39:06Z" depends-on-methods="com.qait.mindtap.tests.NG_30104.NG_30181_TC04_Instructor_Launch_the_Course.Step_01_Instructor_Logs_in_to_the_Application" finished-at="2015-10-01T17:39:27Z">
          <reporter-output>
            <line>
              <![CDATA[[ASSERT PASS]: element pageTitle with text Instructor Resource Center is displayed.]]>
            </line>
            <line>
              <![CDATA[[ASSERT PASS]: element courseOperation with text Manage Course is displayed.]]>
            </line>
          </reporter-output>
        </test-method> <!-- Step_02_Instructor_Manages_Course_From_SSO -->
        <test-method status="PASS" signature="takeScreenshotonFailure(org.testng.ITestResult)[pri:0, instance:com.qait.mindtap.tests.NG_30104.NG_30181_TC04_Instructor_Launch_the_Course@17f6480]" name="takeScreenshotonFailure" is-config="true" duration-ms="2" started-at="2015-10-01T17:39:27Z" finished-at="2015-10-01T17:39:27Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Step_02_Instructor_Manages_Course_From_SSO status=SUCCESS method=NG_30181_TC04_Instructor_Launch_the_Course.Step_02_Instructor_Manages_Course_From_SSO()[pri:0, instance:com.qait.mindtap.tests.NG_30104.NG_30181_TC04_Instructor_Launch_the_Course@17f6480] output=[ASSERT PASS]: element pageTitle with text Instructor Resource Center is displayed.]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- takeScreenshotonFailure -->
        <test-method status="FAIL" signature="Step_03_Instructor_Enrols_TA_IN_Course()[pri:0, instance:com.qait.mindtap.tests.NG_30104.NG_30181_TC04_Instructor_Launch_the_Course@17f6480]" name="Step_03_Instructor_Enrols_TA_IN_Course" duration-ms="56964" started-at="2015-10-01T17:39:27Z" depends-on-methods="com.qait.mindtap.tests.NG_30104.NG_30181_TC04_Instructor_Launch_the_Course.Step_02_Instructor_Manages_Course_From_SSO" finished-at="2015-10-01T17:40:24Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at org.openqa.selenium.support.ui.ExpectedConditions.elementIfVisible(ExpectedConditions.java:302)
	at org.openqa.selenium.support.ui.ExpectedConditions.access$100(ExpectedConditions.java:41)
	at org.openqa.selenium.support.ui.ExpectedConditions$10.apply(ExpectedConditions.java:288)
	at org.openqa.selenium.support.ui.ExpectedConditions$10.apply(ExpectedConditions.java:285)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:209)
	at com.qait.mindtap.automation.utils.SeleniumWait.waitForElementToBeVisible(SeleniumWait.java:53)
	at com.qait.mindtap.automation.getpageobjects.GetPage.isElementDisplayed(GetPage.java:167)
	at com.qait.mindtap.keywords.NG_30104.NG_30181_InstructorEditCourse.instructor_Open_Course(NG_30181_InstructorEditCourse.java:47)
	at com.qait.mindtap.tests.NG_30104.NG_30181_TC04_Instructor_Launch_the_Course.Step_03_Instructor_Enrols_TA_IN_Course(NG_30181_TC04_Instructor_Launch_the_Course.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:91)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:128)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:112)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[[ASSERT PASS]: element btnAddInstructorTA is displayed.]]>
            </line>
            <line>
              <![CDATA[[ASSERT PASS]: element inputEmailId is displayed.]]>
            </line>
            <line>
              <![CDATA[[ASSERT PASS]: element btnAdd is displayed.]]>
            </line>
            <line>
              <![CDATA[[ASSERT FAIL]: Element courseLink not found on the NG-30181-InstructorManageCourses !!!]]>
            </line>
          </reporter-output>
        </test-method> <!-- Step_03_Instructor_Enrols_TA_IN_Course -->
        <test-method status="PASS" signature="takeScreenshotonFailure(org.testng.ITestResult)[pri:0, instance:com.qait.mindtap.tests.NG_30104.NG_30181_TC04_Instructor_Launch_the_Course@17f6480]" name="takeScreenshotonFailure" is-config="true" duration-ms="2" started-at="2015-10-01T17:40:24Z" finished-at="2015-10-01T17:40:24Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Step_03_Instructor_Enrols_TA_IN_Course status=FAILURE method=NG_30181_TC04_Instructor_Launch_the_Course.Step_03_Instructor_Enrols_TA_IN_Course()[pri:0, instance:com.qait.mindtap.tests.NG_30104.NG_30181_TC04_Instructor_Launch_the_Course@17f6480] output=[ASSERT PASS]: element btnAddInstructorTA is displayed.]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- takeScreenshotonFailure -->
        <test-method status="SKIP" signature="Step_04_verify_Spalsh_Page_Dispalys_Automatically()[pri:0, instance:com.qait.mindtap.tests.NG_30104.NG_30181_TC04_Instructor_Launch_the_Course@17f6480]" name="Step_04_verify_Spalsh_Page_Dispalys_Automatically" duration-ms="0" started-at="2015-10-01T17:40:24Z" depends-on-methods="com.qait.mindtap.tests.NG_30104.NG_30181_TC04_Instructor_Launch_the_Course.Step_03_Instructor_Enrols_TA_IN_Course" finished-at="2015-10-01T17:40:24Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method NG_30181_TC04_Instructor_Launch_the_Course.Step_04_verify_Spalsh_Page_Dispalys_Automatically()[pri:0, instance:com.qait.mindtap.tests.NG_30104.NG_30181_TC04_Instructor_Launch_the_Course@17f6480] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method NG_30181_TC04_Instructor_Launch_the_Course.Step_04_verify_Spalsh_Page_Dispalys_Automatically()[pri:0, instance:com.qait.mindtap.tests.NG_30104.NG_30181_TC04_Instructor_Launch_the_Course@17f6480] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:91)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:128)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:112)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Step_04_verify_Spalsh_Page_Dispalys_Automatically -->
        <test-method status="PASS" signature="stop_test_session()[pri:0, instance:com.qait.mindtap.tests.NG_30104.NG_30181_TC04_Instructor_Launch_the_Course@17f6480]" name="stop_test_session" is-config="true" duration-ms="2320" started-at="2015-10-01T17:40:24Z" finished-at="2015-10-01T17:40:26Z">
          <reporter-output>
            <line>
              <![CDATA[[INFO]: The Test: NG_30181_TC03_INSTRUCTOR_CREATES_COURSE COMPLETED!
]]>
            </line>
          </reporter-output>
        </test-method> <!-- stop_test_session -->
        <test-method status="SKIP" signature="Step_07_Instructor_SignOut()[pri:0, instance:com.qait.mindtap.tests.NG_30104.NG_30181_TC04_Instructor_Launch_the_Course@17f6480]" name="Step_07_Instructor_SignOut" duration-ms="0" started-at="2015-10-01T17:40:24Z" depends-on-methods="com.qait.mindtap.tests.NG_30104.NG_30181_TC04_Instructor_Launch_the_Course.Step_08_Verify_Rolling_Week_UI" finished-at="2015-10-01T17:40:24Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method NG_30181_TC04_Instructor_Launch_the_Course.Step_07_Instructor_SignOut()[pri:0, instance:com.qait.mindtap.tests.NG_30104.NG_30181_TC04_Instructor_Launch_the_Course@17f6480] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method NG_30181_TC04_Instructor_Launch_the_Course.Step_07_Instructor_SignOut()[pri:0, instance:com.qait.mindtap.tests.NG_30104.NG_30181_TC04_Instructor_Launch_the_Course@17f6480] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:91)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:128)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:112)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Step_07_Instructor_SignOut -->
        <test-method status="SKIP" signature="Step_07_verify_Splash_Page()[pri:0, instance:com.qait.mindtap.tests.NG_30104.NG_30181_TC04_Instructor_Launch_the_Course@17f6480]" name="Step_07_verify_Splash_Page" duration-ms="0" started-at="2015-10-01T17:40:24Z" depends-on-methods="com.qait.mindtap.tests.NG_30104.NG_30181_TC04_Instructor_Launch_the_Course.Step_06_Verify_Expand_Collapse_Functionality" finished-at="2015-10-01T17:40:24Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method NG_30181_TC04_Instructor_Launch_the_Course.Step_07_verify_Splash_Page()[pri:0, instance:com.qait.mindtap.tests.NG_30104.NG_30181_TC04_Instructor_Launch_the_Course@17f6480] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method NG_30181_TC04_Instructor_Launch_the_Course.Step_07_verify_Splash_Page()[pri:0, instance:com.qait.mindtap.tests.NG_30104.NG_30181_TC04_Instructor_Launch_the_Course@17f6480] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:91)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:128)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:112)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Step_07_verify_Splash_Page -->
        <test-method status="SKIP" signature="Step_05_Verify_Weeks_CurrentWeekIcon_Displays_Along_Month_and_Date()[pri:0, instance:com.qait.mindtap.tests.NG_30104.NG_30181_TC04_Instructor_Launch_the_Course@17f6480]" name="Step_05_Verify_Weeks_CurrentWeekIcon_Displays_Along_Month_and_Date" duration-ms="0" started-at="2015-10-01T17:40:24Z" depends-on-methods="com.qait.mindtap.tests.NG_30104.NG_30181_TC04_Instructor_Launch_the_Course.Step_04_verify_Spalsh_Page_Dispalys_Automatically" finished-at="2015-10-01T17:40:24Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method NG_30181_TC04_Instructor_Launch_the_Course.Step_05_Verify_Weeks_CurrentWeekIcon_Displays_Along_Month_and_Date()[pri:0, instance:com.qait.mindtap.tests.NG_30104.NG_30181_TC04_Instructor_Launch_the_Course@17f6480] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method NG_30181_TC04_Instructor_Launch_the_Course.Step_05_Verify_Weeks_CurrentWeekIcon_Displays_Along_Month_and_Date()[pri:0, instance:com.qait.mindtap.tests.NG_30104.NG_30181_TC04_Instructor_Launch_the_Course@17f6480] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:91)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:128)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:112)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Step_05_Verify_Weeks_CurrentWeekIcon_Displays_Along_Month_and_Date -->
        <test-method status="SKIP" signature="Step_06_Verify_Expand_Collapse_Functionality()[pri:0, instance:com.qait.mindtap.tests.NG_30104.NG_30181_TC04_Instructor_Launch_the_Course@17f6480]" name="Step_06_Verify_Expand_Collapse_Functionality" duration-ms="0" started-at="2015-10-01T17:40:24Z" depends-on-methods="com.qait.mindtap.tests.NG_30104.NG_30181_TC04_Instructor_Launch_the_Course.Step_05_Verify_Weeks_CurrentWeekIcon_Displays_Along_Month_and_Date" finished-at="2015-10-01T17:40:24Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method NG_30181_TC04_Instructor_Launch_the_Course.Step_06_Verify_Expand_Collapse_Functionality()[pri:0, instance:com.qait.mindtap.tests.NG_30104.NG_30181_TC04_Instructor_Launch_the_Course@17f6480] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method NG_30181_TC04_Instructor_Launch_the_Course.Step_06_Verify_Expand_Collapse_Functionality()[pri:0, instance:com.qait.mindtap.tests.NG_30104.NG_30181_TC04_Instructor_Launch_the_Course@17f6480] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:91)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:128)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:112)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Step_06_Verify_Expand_Collapse_Functionality -->
        <test-method status="SKIP" signature="Step_08_Verify_Rolling_Week_UI()[pri:0, instance:com.qait.mindtap.tests.NG_30104.NG_30181_TC04_Instructor_Launch_the_Course@17f6480]" name="Step_08_Verify_Rolling_Week_UI" duration-ms="0" started-at="2015-10-01T17:40:24Z" depends-on-methods="com.qait.mindtap.tests.NG_30104.NG_30181_TC04_Instructor_Launch_the_Course.Step_07_verify_Splash_Page" finished-at="2015-10-01T17:40:24Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method NG_30181_TC04_Instructor_Launch_the_Course.Step_08_Verify_Rolling_Week_UI()[pri:0, instance:com.qait.mindtap.tests.NG_30104.NG_30181_TC04_Instructor_Launch_the_Course@17f6480] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method NG_30181_TC04_Instructor_Launch_the_Course.Step_08_Verify_Rolling_Week_UI()[pri:0, instance:com.qait.mindtap.tests.NG_30104.NG_30181_TC04_Instructor_Launch_the_Course@17f6480] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:91)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:128)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:112)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Step_08_Verify_Rolling_Week_UI -->
      </class> <!-- com.qait.mindtap.tests.NG_30104.NG_30181_TC04_Instructor_Launch_the_Course -->
    </test> <!-- Command line test 8a156310-bcfb-4614-854c-9563abd6972e -->
  </suite> <!-- com.qait.mindtap.tests.NG_30104.NG_30181_TC04_Instructor_Launch_the_Course -->
</testng-results>
